server:
  port: 8050
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product
    username: root
    password: azerty12346
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
# Configuration for Axon
axon:
  eventhandling:
    processors:
      tracking:
        mode: tracking
        source: eventStore
        initial-segment-count: 1

  eventstore:
    jpa:
      schema-generation:
        enabled: true
